export const iconList = [
    'Accessibility', 'Activity', 'AirVent', 'AirPlay', 'AlarmClockOff', 'AlarmClock', 
    'Album', 'AlertCircle', 'AlertOctagon', 'AlertTriangle', 'AlignCenter', 'AlignJustify', 
    'AlignLeft', 'AlignRight', 'Anchor', 'Aperture', 'Archive', 'ArrowBigDown', 
    'ArrowBigLeft', 'ArrowBigRight', 'ArrowBigUp', 'ArrowDownCircle', 'ArrowDownLeft', 
    'ArrowDownRight', 'ArrowDown', 'ArrowLeftCircle', 'ArrowLeftRight', 'ArrowLeft', 
    'ArrowRightCircle', 'ArrowRight', 'ArrowUpCircle', 'ArrowUpDown', 'ArrowUpLeft', 
    'ArrowUpRight', 'ArrowUp', 'Asterisk', 'AtSign', 'Award', 'Axe', 'Backpack', 'BaggageClaim', 
    'Ban', 'Banknote', 'BarChart2', 'BarChart', 'BatteryCharging', 'BatteryFull', 'BatteryLow', 
    'BatteryMedium', 'Battery', 'Beaker', 'Bed', 'BellMinus', 'BellOff', 'BellPlus', 'BellRing', 
    'Bell', 'Bike', 'Binary', 'Bitcoin', 'BluetoothConnected', 'BluetoothOff', 'BluetoothSearching', 
    'Bluetooth', 'Bold', 'BookOpen', 'Book', 'BookmarkMinus', 'BookmarkPlus', 'Bookmark', 
    'Bot', 'BoxSelect', 'Box', 'Briefcase', 'Brush', 'Bug', 'Building', 'BulbOff', 'Bulb', 
    'CalendarCheck', 'CalendarClock', 'CalendarDays', 'CalendarMinus', 'CalendarPlus', 
    'CalendarRange', 'CalendarX', 'Calendar', 'CameraOff', 'Camera', 'Candy', 'Car', 
    'Carrot', 'Cast', 'Cat', 'CheckCircle2', 'CheckCircle', 'CheckSquare', 'Check', 
    'ChevronDown', 'ChevronFirst', 'ChevronLast', 'ChevronLeft', 'ChevronRight', 'ChevronUp', 
    'ChevronsDownUp', 'ChevronsDown', 'ChevronsLeftRight', 'ChevronsLeft', 'ChevronsRightLeft', 
    'ChevronsRight', 'ChevronsUpDown', 'ChevronsUp', 'Chrome', 'Church', 'CircleDot', 
    'CircleEllipsis', 'CircleEqual', 'CircleSlash2', 'CircleSlash', 'Circle', 'CircuitBoard', 
    'Citrus', 'Clapperboard', 'ClipboardCheck', 'ClipboardCopy', 'ClipboardEdit', 
    'ClipboardList', 'ClipboardSignature', 'ClipboardType', 'ClipboardX', 'Clipboard', 
    'Clock1', 'Clock10', 'Clock11', 'Clock12', 'Clock2', 'Clock3', 'Clock4', 'Clock5', 
    'Clock6', 'Clock7', 'Clock8', 'Clock9', 'Clock', 'CloudCog', 'CloudDrizzle', 'CloudFog', 
    'CloudHail', 'CloudLightning', 'CloudMoonRain', 'CloudMoon', 'CloudOff', 'CloudRainWind', 
    'CloudRain', 'CloudSnow', 'CloudSunRain', 'CloudSun', 'Cloud', 'Cloudy', 'Clover', 'Code2', 
    'Code', 'Codepen', 'Codesandbox', 'Coffee', 'Cog', 'Coins', 'Columns', 'Command', 'Compass', 
    'Component', 'ConciergeBell', 'Construction', 'Contact2', 'Contact', 'Contrast', 'Cookie', 
    'CopyCheck', 'CopyMinus', 'CopyPlus', 'CopySlash', 'CopyX', 'Copy', 'Copyleft', 'Copyright', 
    'CornerDownLeft', 'CornerDownRight', 'CornerLeftDown', 'CornerLeftUp', 'CornerRightDown', 
    'CornerRightUp', 'CornerUpLeft', 'CornerUpRight', 'Cpu', 'CreativeCommons', 'CreditCard', 
    'Croissant', 'Crop', 'Cross', 'Crosshair', 'Crown', 'CupSoda', 'CurlyBraces', 'Currency', 
    'DatabaseBackup', 'Database', 'Delete', 'Disc2', 'Disc3', 'Disc', 'DivideCircle', 
    'DivideSquare', 'Divide', 'DnaOff', 'Dna', 'Dog', 'DollarSign', 'DoorClosed', 'DoorOpen', 
    'Dot', 'DownloadCloud', 'Download', 'Dribbble', 'Droplet', 'Droplets', 'Drumstick', 
    'Dumbbell', 'EarOff', 'Ear', 'Edit2', 'Edit3', 'Edit', 'EggFried', 'EggOff', 'Egg', 
    'EqualNot', 'Equal', 'Eraser', 'Euro', 'Expand', 'ExternalLink', 'EyeOff', 'Eye', 'Facebook', 
    'Factory', 'Fan', 'FastForward', 'Feather', 'Figma', 'FileArchive', 'FileAudio2', 
    'FileAudio', 'FileAxis3D', 'FileBadge2', 'FileBadge', 'FileBarChart2', 'FileBarChart', 
    'FileBox', 'FileCheck2', 'FileCheck', 'FileClock', 'FileCode2', 'FileCode', 'FileCog2', 
    'FileCog', 'FileDiff', 'FileDigit', 'FileDown', 'FileEdit', 'FileHeart', 'FileImage', 
    'FileInput', 'FileJson2', 'FileJson', 'FileKey2', 'FileKey', 'FileLineChart', 'FileLock2', 
    'FileLock', 'FileMinus2', 'FileMinus', 'FileOutput', 'FilePieChart', 'FilePlus2', 'FilePlus', 
    'FileQuestion', 'FileScan', 'FileSearch2', 'FileSearch', 'FileSignature', 'FileSpreadsheet', 
    'FileSymlink', 'FileTerminal', 'FileText', 'FileType2', 'FileType', 'FileUp', 'FileVideo2', 
    'FileVideo', 'FileVolume2', 'FileVolume', 'FileWarning', 'FileX2', 'FileX', 'File', 
    'Files', 'Film', 'FilterX', 'Filter', 'Fingerprint', 'FishOff', 'Fish', 'FlagOff', 'FlagTriangleLeft', 
    'FlagTriangleRight', 'Flag', 'Flame', 'FlashlightOff', 'Flashlight', 'FlaskConicalOff', 
    'FlaskConical', 'FlaskRound', 'FlipHorizontal2', 'FlipHorizontal', 'FlipVertical2', 
    'FlipVertical', 'Flower2', 'Flower', 'Focus', 'FoldHorizontal', 'FoldVertical', 'FolderArchive', 
    'FolderCheck', 'FolderClock', 'FolderClosed', 'FolderCog2', 'FolderCog', 'FolderDown', 
    'FolderEdit', 'FolderHeart', 'FolderInput', 'FolderKey', 'FolderLock', 'FolderMinus', 
    'FolderOpen', 'FolderOutput', 'FolderPlus', 'FolderSearch2', 'FolderSearch', 'FolderSymlink', 
    'FolderTree', 'FolderUp', 'FolderX', 'Folder', 'Folders', 'Footprints', 'Forklift', 
    'FormInput', 'Forward', 'Frame', 'Framer', 'Frown', 'Fuel', 'FunctionSquare', 'Gamepad2', 
    'Gamepad', 'Gauge', 'Gavel', 'Gem', 'Ghost', 'Gift', 'GitBranchPlus', 'GitBranch', 
    'GitCommit', 'GitCompare', 'GitFork', 'GitMerge', 'GitPullRequestClosed', 'GitPullRequestDraft', 
    'GitPullRequest', 'Github', 'Gitlab', 'Glasses', 'Globe2', 'Globe', 'Grab', 'GraduationCap', 
    'Grape', 'Grid', 'GripHorizontal', 'GripVertical', 'Hammer', 'HandMetal', 'Hand', 
    'HardDrive', 'HardHat', 'Hash', 'Haze', 'Heading1', 'Heading2', 'Heading3', 'Heading4', 
    'Heading5', 'Heading6', 'Heading', 'Headphones', 'HeartCrack', 'HeartHandshake', 'HeartOff', 
    'HeartPulse', 'Heart', 'HelpCircle', 'HelpingHand', 'Hexagon', 'Highlighter', 'History', 
    'Home', 'Hop', 'HopOff', 'Hotel', 'Hourglass', 'IceCream2', 'IceCream', 'ImageMinus', 
    'ImageOff', 'ImagePlus', 'Image', 'Import', 'Inbox', 'Indent', 'IndianRupee', 'Infinity', 
    'Info', 'Inspect', 'Instagram', 'Italic', 'JapaneseYen', 'Joystick', 'KeyRound', 'KeySquare', 
    'Key', 'Keyboard', 'LampCeiling', 'LampDesk', 'LampFloor', 'LampWallDown', 'LampWallUp', 
    'Lamp', 'Landmark', 'Languages', 'Laptop2', 'Laptop', 'LassoSelect', 'Lasso', 'Laugh', 
    'Layers', 'LayoutDashboard', 'LayoutGrid', 'LayoutList', 'LayoutTemplate', 'Layout', 'Leaf', 
    'LeafyGreen', 'Library', 'LifeBuoy', 'Ligature', 'LightbulbOff', 'LightbulbHere']